create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users on delete cascade, email text, role text not null default 'user' check (role in ('user','admin')), created_at timestamptz default now());
create table if not exists public.source_documents (id uuid primary key default gen_random_uuid(), original_filename text not null, normalized_filename text not null, storage_path text, mime_type text, file_size bigint, sha256 text not null unique, exam_year int, exam_round int, page_count int, extraction_method text, extraction_status text, question_count int default 0, is_duplicate boolean default false, duplicate_of uuid references public.source_documents, error_message text, imported_at timestamptz default now(), created_at timestamptz default now());
create table if not exists public.exam_sets (id uuid primary key default gen_random_uuid(), year int not null, round int not null, title text not null, total_questions int default 0, expected_questions int default 100, source_document_id uuid references public.source_documents, validation_status text default 'needs_review', is_published boolean default false, created_at timestamptz default now(), updated_at timestamptz default now(), unique(year,round));
create table if not exists public.subjects (id smallserial primary key, name text unique not null, display_order int not null);
insert into public.subjects(name,display_order) values ('소프트웨어 설계',1),('소프트웨어 개발',2),('데이터베이스 구축',3),('프로그래밍 언어 활용',4),('정보시스템 구축관리',5) on conflict do nothing;
create table if not exists public.questions (id uuid primary key default gen_random_uuid(), exam_set_id uuid not null references public.exam_sets on delete cascade, subject_id smallint references public.subjects, question_no int not null, question_text text not null, passage text, question_type text default 'multiple_choice', code_language text, code_content text, table_data jsonb, source_page int, source_text text, normalized_hash text not null, extraction_confidence numeric, needs_review boolean default false, is_published boolean default false, source_type text default 'uploaded_exam_pdf', scope_status text default 'mapped', is_code boolean default false, is_sql boolean default false, created_at timestamptz default now(), updated_at timestamptz default now(), unique(exam_set_id,question_no));
create table if not exists public.question_choices (id uuid primary key default gen_random_uuid(), question_id uuid not null references public.questions on delete cascade, choice_key text not null check(choice_key in ('A','B','C','D')), choice_text text not null, original_choice_text text, display_order int not null, asset_id uuid, created_at timestamptz default now(), unique(question_id,choice_key));
create table if not exists public.question_solutions (id uuid primary key default gen_random_uuid(), question_id uuid not null unique references public.questions on delete cascade, correct_answer text check(correct_answer in ('A','B','C','D')), original_answer_text text, explanation text, choice_explanations jsonb, related_concepts jsonb, memory_tip text, practical_point text, explanation_status text default 'missing', explanation_source text, is_verified boolean default false, verification_note text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.question_assets (id uuid primary key default gen_random_uuid(), question_id uuid references public.questions on delete cascade, source_document_id uuid references public.source_documents, page_number int, asset_type text, storage_path text, alt_text text, display_order int, width int, height int, sha256 text, created_at timestamptz default now());
create table if not exists public.exam_attempts (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users on delete cascade, mode text not null, score int, total int, answers jsonb not null default '{}', completed_at timestamptz, created_at timestamptz default now());
create table if not exists public.user_question_state (user_id uuid references auth.users on delete cascade, question_id uuid references public.questions on delete cascade, is_bookmarked boolean default false, attempts int default 0, correct_count int default 0, wrong_count int default 0, last_answer text, updated_at timestamptz default now(), primary key(user_id,question_id));
create table if not exists public.exam_standards (id uuid primary key default gen_random_uuid(), title text not null, effective_from date, effective_to date, source_document_id uuid references public.source_documents, raw_text text, parsed_structure jsonb, sha256 text unique, created_at timestamptz default now());
create table if not exists public.exam_standard_items (id uuid primary key default gen_random_uuid(), exam_standard_id uuid references public.exam_standards on delete cascade, subject_name text, major_category text, middle_category text, minor_category text, details text, source_page int, display_order int);
alter table public.question_solutions enable row level security; alter table public.exam_attempts enable row level security; alter table public.user_question_state enable row level security;
drop policy if exists "own attempts" on public.exam_attempts; create policy "own attempts" on public.exam_attempts for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "own state" on public.user_question_state; create policy "own state" on public.user_question_state for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
-- question_solutions intentionally has no client SELECT policy; grading is server-only.
insert into storage.buckets(id,name,public) values ('exam-source-pdfs','exam-source-pdfs',false),('question-assets','question-assets',false),('exam-standards','exam-standards',false) on conflict(id) do update set public=false;
